imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: database.yml }
    - { resource: services.yml }
    - { resource: "@HotelsBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    serializer:
        enabled: true
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"


# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }
    
fos_rest:
    param_fetcher_listener: true
    view:
        view_response_listener: 'force'
        formats:
            xml: true
            json: true
        templating_formats:
            html: false
    format_listener:
        rules:
            - { path: '^/api', priorities: [ 'json','html'], fallback_format: ~, prefer_extension: false }
            - { path: '^/', priorities: [ 'html', 'json', 'xml' ], fallback_format: ~, prefer_extension: false }
    exception:
        enabled: true
        exception_controller: 'HotelsBundle\Controller\ExceptionController::showAction'
        codes:
            'Symfony\Component\HttpKernel\Exception\NotFoundHttpException': 404
            'Symfony\Component\HttpKernel\Exception\BadRequestHttpException': 400
            'Symfony\Component\HttpKernel\Exception\ConflictHttpException': 409
            'Doctrine\ORM\OptimisticLockException': HTTP_CONFLICT
            'Symfony\Component\Security\Core\Exception\AuthenticationException': 401
        messages:
            'Symfony\Component\HttpKernel\Exception\NotFoundHttpException': true
            'Symfony\Component\HttpKernel\Exception\BadRequestHttpException': true
            'Symfony\Component\HttpKernel\Exception\ConflictHttpException': true
            'Symfony\Component\Security\Core\Exception\AuthenticationException': true
    allowed_methods_listener: true
    body_listener: true
    disable_csrf_role: ROLE_API
    routing_loader:
        default_format: json
    serializer:
        serialize_null: true
